// lib/tools-data.ts
// Single source of truth for all 88 SarkariPixels tools
// Used for SSR page generation, sitemap, and navigation

export type ToolCategory =
  | "most-used"
  | "basic-edit"
  | "effects"
  | "dpi-quality"
  | "id-sizes"
  | "general-compress"
  | "target-sizes"
  | "official-sizes";

export interface Tool {
  id: string;
  category: ToolCategory;
  icon: string;
  title: string;
  desc: string;
  group: string;
  // Optional fields
  defaultKB?: number;
  targetKB?: number;
  defaultW?: number;
  defaultH?: number;
  unit?: "px" | "cm" | "mm" | "inch";
  dpi?: number;
  filterType?: string;
  stampType?: string;
  censorType?: string;
  borderType?: string;
  aspect?: number;
  cropStyle?: string;
  format?: string;
  subGroup?: string;
  forceSquare?: boolean;
}

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  "most-used": "Most Used Tools",
  "basic-edit": "Basic Editing",
  effects: "Blur, Pixelate & Special Effects",
  "dpi-quality": "DPI & Quality",
  "id-sizes": "Passport & ID Photo Sizes",
  "general-compress": "General Compression",
  "target-sizes": "Exact Target Sizes",
  "official-sizes": "Resize Other Official Sizes",
};

export const CATEGORY_COUNTS: Record<ToolCategory, number> = {
  "most-used": 11,
  "basic-edit": 18,
  effects: 19,
  "dpi-quality": 4,
  "id-sizes": 9,
  "general-compress": 6,
  "target-sizes": 16,
  "official-sizes": 5,
};

export const TOOLS: Tool[] = [
  // ── 1. Most Used Tools (11) ──────────────────────────────────────────────
  {
    id: "smart-resizer",
    category: "most-used",
    icon: "fa-up-right-and-down-left-from-center",
    title: "Smart Image Resizer",
    desc: "Resize photos and images online in pixels, inches, or mm. Instant results.",
    group: "universal-resize",
  },
  {
    id: "passport-maker",
    category: "most-used",
    icon: "fa-address-card",
    title: "Passport Photo Maker",
    desc: "Create printable multi-photo sheets.",
    group: "id-grid",
  },
  {
    id: "reduce-kb",
    category: "most-used",
    icon: "fa-compress-arrows-alt",
    title: "Reduce Image Size in KB",
    desc: "Compress image file footprint.",
    group: "compress",
    defaultKB: 50,
  },
  {
    id: "resize-pixel",
    category: "most-used",
    icon: "fa-up-right-and-down-left-from-center",
    title: "Resize Image Pixel",
    desc: "Scale dimensions in pixels.",
    group: "resize",
    defaultW: 800,
    defaultH: 600,
    unit: "px",
  },
  {
    id: "collage-maker",
    category: "most-used",
    icon: "fa-grip",
    title: "Photo Collage Maker",
    desc: "Combine photos into a collage grid.",
    group: "collage",
  },
  {
    id: "generate-signature",
    category: "most-used",
    icon: "fa-signature",
    title: "Generate Signature",
    desc: "Type/Draw digital signatures.",
    group: "signature",
  },
  {
    id: "increase-kb",
    category: "most-used",
    icon: "fa-expand-arrows-alt",
    title: "Increase Image Size In KB",
    desc: "Pads binary EXIF blocks with dummy bits.",
    group: "increase-compress",
  },
  {
    id: "photo-enhancer",
    category: "most-used",
    icon: "fa-wand-magic-sparkles",
    title: "AI Photo Enhancer",
    desc: "Adjust contrast and details.",
    group: "filter",
    filterType: "enhance",
  },
  {
    id: "resize-signature",
    category: "most-used",
    icon: "fa-pencil",
    title: "Resize Signature",
    desc: "Adjust signature sizes for forms.",
    group: "resize",
    defaultW: 400,
    defaultH: 200,
    unit: "px",
  },
  {
    id: "resize-cm",
    category: "most-used",
    icon: "fa-ruler",
    title: "Resize Image In Centimeter",
    desc: "Set size in centimeters.",
    group: "resize",
    defaultW: 3.5,
    defaultH: 4.5,
    unit: "cm",
  },
  {
    id: "resize-35-45",
    category: "most-used",
    icon: "fa-crop-simple",
    title: "Resize Image (3.5cm x 4.5cm)",
    desc: "Quick fit to 3.5 x 4.5 cm.",
    group: "resize",
    defaultW: 3.5,
    defaultH: 4.5,
    unit: "cm",
  },

  // ── 2. Basic Editing (18) ────────────────────────────────────────────────
  {
    id: "blur-bg",
    category: "basic-edit",
    icon: "fa-image",
    title: "Blur Background",
    desc: "Soften details behind central portrait.",
    group: "filter",
    filterType: "blur-bg",
  },
  {
    id: "remove-bg",
    category: "basic-edit",
    icon: "fa-eraser",
    title: "Remove Background",
    desc: "Wipe paper shadows to white.",
    group: "filter",
    filterType: "remove-bg",
  },
  {
    id: "remove-object",
    category: "basic-edit",
    icon: "fa-brush",
    title: "Remove Object from Photo",
    desc: "Mask out details or ink stains.",
    group: "draw-mask",
  },
  {
    id: "add-name-dob",
    category: "basic-edit",
    icon: "fa-calendar-day",
    title: "Add Name & DOB on Photo",
    desc: "Overlay bottom strip with details.",
    group: "text-overlay",
    stampType: "name-dob",
  },
  {
    id: "rotate-image",
    category: "basic-edit",
    icon: "fa-rotate",
    title: "Rotate Image",
    desc: "Rotate orientation.",
    group: "rotate",
  },
  {
    id: "flip-image",
    category: "basic-edit",
    icon: "fa-arrows-left-right",
    title: "Flip Image",
    desc: "Mirror horizontal/vertical.",
    group: "flip",
  },
  {
    id: "watermark-image",
    category: "basic-edit",
    icon: "fa-copyright",
    title: "Watermark Images",
    desc: "Overlay copyright text.",
    group: "text-overlay",
    stampType: "watermark",
  },
  {
    id: "free-crop",
    category: "basic-edit",
    icon: "fa-crop",
    title: "Freehand Crop",
    desc: "Crop freely using boundaries.",
    group: "crop",
  },
  {
    id: "circle-crop",
    category: "basic-edit",
    icon: "fa-circle-dot",
    title: "Circle Crop",
    desc: "Crop into clean circular form.",
    group: "crop",
    aspect: 1,
    cropStyle: "circle",
  },
  {
    id: "square-crop",
    category: "basic-edit",
    icon: "fa-square",
    title: "Square Crop",
    desc: "Crop to square aspect.",
    group: "crop",
    aspect: 1,
  },
  {
    id: "merge-photo-sig",
    category: "basic-edit",
    icon: "fa-grip-vertical",
    title: "Merge Photo & Signature",
    desc: "Combine photo/signature.",
    group: "merge",
  },
  {
    id: "join-images",
    category: "basic-edit",
    icon: "fa-object-group",
    title: "Join Multiple Images",
    desc: "Join multiple files together.",
    group: "join",
  },
  {
    id: "split-image",
    category: "basic-edit",
    icon: "fa-scissors",
    title: "Split Image",
    desc: "Split scans into halves.",
    group: "split",
  },
  {
    id: "color-picker",
    category: "basic-edit",
    icon: "fa-eye-dropper",
    title: "Image Color Picker",
    desc: "Extract pixel color code.",
    group: "color-picker",
  },
  {
    id: "edit-metadata",
    category: "basic-edit",
    icon: "fa-pen-to-square",
    title: "Edit Metadata",
    desc: "Set author and title headers.",
    group: "metadata",
    subGroup: "edit",
  },
  {
    id: "view-metadata",
    category: "basic-edit",
    icon: "fa-tags",
    title: "View Metadata",
    desc: "Show EXIF and DPI metadata.",
    group: "metadata",
    subGroup: "view",
  },
  {
    id: "remove-metadata",
    category: "basic-edit",
    icon: "fa-eye-slash",
    title: "Remove Metadata",
    desc: "Erase camera metadata tags.",
    group: "metadata",
    subGroup: "remove",
  },
  {
    id: "crop-png",
    category: "basic-edit",
    icon: "fa-file-image",
    title: "Crop PNG",
    desc: "Crop files with alpha transparency.",
    group: "crop",
    format: "image/png",
  },

  // ── 3. Blur, Pixelate & Special Effects (19) ─────────────────────────────
  {
    id: "beautify",
    category: "effects",
    icon: "fa-face-smile",
    title: "Beautify Image",
    desc: "Smooth skin textures.",
    group: "filter",
    filterType: "beautify",
  },
  {
    id: "unblur",
    category: "effects",
    icon: "fa-compress",
    title: "Unblur Image",
    desc: "Sharpen text blur.",
    group: "filter",
    filterType: "sharpen",
  },
  {
    id: "blur-image",
    category: "effects",
    icon: "fa-circle-half-stroke",
    title: "Blur Image",
    desc: "Soften entire image pixels.",
    group: "filter",
    filterType: "blur",
  },
  {
    id: "blur-face",
    category: "effects",
    icon: "fa-ghost",
    title: "Blur Face",
    desc: "Mask center oval face.",
    group: "filter",
    filterType: "blur-face",
  },
  {
    id: "unblur-face",
    category: "effects",
    icon: "fa-face-viewfinder",
    title: "Unblur Face",
    desc: "Sharpen face region.",
    group: "filter",
    filterType: "unblur-face",
  },
  {
    id: "add-border",
    category: "effects",
    icon: "fa-border-all",
    title: "Add Border To Image",
    desc: "Paint solid border frame.",
    group: "draw-border",
    borderType: "normal",
  },
  {
    id: "pixelate",
    category: "effects",
    icon: "fa-table-cells",
    title: "Pixelate Image",
    desc: "Procedural pixel squares.",
    group: "filter",
    filterType: "pixelate",
  },
  {
    id: "pixelate-face",
    category: "effects",
    icon: "fa-qrcode",
    title: "Pixelate Face",
    desc: "Censor face with pixel blocks.",
    group: "filter",
    filterType: "pixelate-face",
  },
  {
    id: "censor-photo",
    category: "effects",
    icon: "fa-rectangle-ad",
    title: "Censor Photo",
    desc: "Censor zones with black bars.",
    group: "draw-mask",
    censorType: "black-bar",
  },
  {
    id: "motion-blur",
    category: "effects",
    icon: "fa-wind",
    title: "Motion Blur",
    desc: "Apply movement blur.",
    group: "filter",
    filterType: "motion-blur",
  },
  {
    id: "grayscale",
    category: "effects",
    icon: "fa-droplet-slash",
    title: "Grayscale Image",
    desc: "Remove color channels.",
    group: "filter",
    filterType: "grayscale",
  },
  {
    id: "black-white",
    category: "effects",
    icon: "fa-moon",
    title: "Black & White",
    desc: "High contrast binary threshold.",
    group: "filter",
    filterType: "threshold",
  },
  {
    id: "pixel-art",
    category: "effects",
    icon: "fa-gamepad",
    title: "Picture to Pixel Art",
    desc: "Convert photo to 8-bit style.",
    group: "filter",
    filterType: "pixel-art",
  },
  {
    id: "add-white-border",
    category: "effects",
    icon: "fa-square-plus",
    title: "Add White Border To Image",
    desc: "Overlay white borders.",
    group: "draw-border",
    borderType: "white",
  },
  {
    id: "ai-face",
    category: "effects",
    icon: "fa-robot",
    title: "AI Face Generator",
    desc: "Create random dummy face.",
    group: "ai-face",
  },
  {
    id: "blemish-remover",
    category: "effects",
    icon: "fa-circle-check",
    title: "Blemishes Remover",
    desc: "Clear spot blemishes.",
    group: "filter",
    filterType: "blemish",
  },
  {
    id: "retouch",
    category: "effects",
    icon: "fa-sparkles",
    title: "Retouch Image",
    desc: "Adjust lighting balance.",
    group: "filter",
    filterType: "retouch",
  },
  {
    id: "add-text",
    category: "effects",
    icon: "fa-t",
    title: "Add Text to Image",
    desc: "Write text overlays.",
    group: "text-overlay",
    stampType: "text",
  },
  {
    id: "add-logo",
    category: "effects",
    icon: "fa-file-shield",
    title: "Add Logo to Image",
    desc: "Draw logo overlays.",
    group: "logo-overlay",
  },

  // ── 4. DPI & Quality (4) ─────────────────────────────────────────────────
  {
    id: "increase-quality",
    category: "dpi-quality",
    icon: "fa-chart-line",
    title: "Increase Image Quality",
    desc: "Upscale resolution details.",
    group: "filter",
    filterType: "upscale",
  },
  {
    id: "convert-dpi",
    category: "dpi-quality",
    icon: "fa-print",
    title: "Convert DPI (200, 300, 600)",
    desc: "Modify DPI metadata resolution.",
    group: "dpi",
  },
  {
    id: "check-dpi",
    category: "dpi-quality",
    icon: "fa-info",
    title: "Check Image DPI",
    desc: "Verify current resolution tags.",
    group: "dpi-check",
  },
  {
    id: "super-res",
    category: "dpi-quality",
    icon: "fa-maximize",
    title: "Super Resolution",
    desc: "Upscale with sharp detailing.",
    group: "filter",
    filterType: "super-res",
  },

  // ── 5. Passport & ID Photo Sizes (9) ─────────────────────────────────────
  {
    id: "pass-photo-sizes",
    category: "id-sizes",
    icon: "fa-address-card",
    title: "Passport Photo Maker",
    desc: "Grid sheets generator.",
    group: "id-grid",
  },
  {
    id: "resize-sign-6-2",
    category: "id-sizes",
    icon: "fa-signature",
    title: "Resize Sign 6cm x 2cm",
    desc: "Sign resizer (6x2cm at 300 DPI).",
    group: "resize",
    defaultW: 6,
    defaultH: 2,
    unit: "cm",
    dpi: 300,
  },
  {
    id: "resize-sign-35-45",
    category: "id-sizes",
    icon: "fa-crop-simple",
    title: "3.5cm x 4.5cm Signature",
    desc: "Resize signature to 3.5 x 4.5 cm.",
    group: "resize",
    defaultW: 3.5,
    defaultH: 4.5,
    unit: "cm",
  },
  {
    id: "resize-50-20",
    category: "id-sizes",
    icon: "fa-ruler-combined",
    title: "50mm x 20mm",
    desc: "Resize signature to 50x20 mm.",
    group: "resize",
    defaultW: 50,
    defaultH: 20,
    unit: "mm",
  },
  {
    id: "resize-35-45-mm",
    category: "id-sizes",
    icon: "fa-ruler-horizontal",
    title: "35mm x 45mm",
    desc: "Resize photo to 35x45 mm.",
    group: "resize",
    defaultW: 35,
    defaultH: 45,
    unit: "mm",
  },
  {
    id: "resize-2-2",
    category: "id-sizes",
    icon: "fa-id-badge",
    title: "2 x 2 Inch",
    desc: "Resize photo to 2x2 inches.",
    group: "resize",
    defaultW: 2,
    defaultH: 2,
    unit: "inch",
  },
  {
    id: "resize-3-4",
    category: "id-sizes",
    icon: "fa-rectangle-list",
    title: "3 x 4 Inch",
    desc: "Resize photo to 3x4 inches.",
    group: "resize",
    defaultW: 3,
    defaultH: 4,
    unit: "inch",
  },
  {
    id: "resize-4-6",
    category: "id-sizes",
    icon: "fa-images",
    title: "4 x 6 Inch",
    desc: "Resize photo to 4x6 inches.",
    group: "resize",
    defaultW: 4,
    defaultH: 6,
    unit: "inch",
  },
  {
    id: "resize-600-600",
    category: "id-sizes",
    icon: "fa-border-none",
    title: "600x600 Pixels",
    desc: "Scale photo to 600x600 px.",
    group: "resize",
    defaultW: 600,
    defaultH: 600,
    unit: "px",
  },

  // ── 6. General Compression (6) ───────────────────────────────────────────
  {
    id: "compress-general",
    category: "general-compress",
    icon: "fa-box-archive",
    title: "Image Compressor",
    desc: "Compress image sizes.",
    group: "compress",
    defaultKB: 50,
  },
  {
    id: "reduce-kb-general",
    category: "general-compress",
    icon: "fa-down-left-and-up-right-to-center",
    title: "Reduce Size in KB",
    desc: "Compress to custom KB bounds.",
    group: "compress",
    defaultKB: 20,
  },
  {
    id: "reduce-mb",
    category: "general-compress",
    icon: "fa-file-lines",
    title: "Reduce Size in MB",
    desc: "Compress MB down to target limits.",
    group: "compress",
    defaultKB: 1024,
  },
  {
    id: "jpg-to-kb",
    category: "general-compress",
    icon: "fa-arrow-down-short-wide",
    title: "JPG to KB",
    desc: "Fit JPG under custom limits.",
    group: "compress",
    defaultKB: 30,
  },
  {
    id: "convert-mb-to-kb",
    category: "general-compress",
    icon: "fa-calculator",
    title: "Convert MB to KB",
    desc: "Reduce MB files down to KB scale.",
    group: "compress",
    defaultKB: 100,
  },
  {
    id: "convert-kb-to-mb",
    category: "general-compress",
    icon: "fa-chart-pie",
    title: "Convert KB to MB",
    desc: "Pad files or upscale to MB bounds.",
    group: "compress",
    defaultKB: 2048,
  },

  // ── 7. Exact Target Sizes (16) ───────────────────────────────────────────
  {
    id: "compress-5",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 5KB",
    desc: "Force file size under 5KB limit.",
    group: "compress",
    targetKB: 5,
  },
  {
    id: "compress-10",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 10KB",
    desc: "Force file size under 10KB limit.",
    group: "compress",
    targetKB: 10,
  },
  {
    id: "compress-15",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 15KB",
    desc: "Force file size under 15KB limit.",
    group: "compress",
    targetKB: 15,
  },
  {
    id: "compress-20",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 20KB",
    desc: "Force file size under 20KB limit.",
    group: "compress",
    targetKB: 20,
  },
  {
    id: "compress-20-50",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress 20KB-50KB",
    desc: "Fits file size within 20-50KB.",
    group: "compress",
    targetKB: 35,
  },
  {
    id: "compress-25",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 25KB",
    desc: "Force file size under 25KB limit.",
    group: "compress",
    targetKB: 25,
  },
  {
    id: "compress-30",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 30KB",
    desc: "Force file size under 30KB limit.",
    group: "compress",
    targetKB: 30,
  },
  {
    id: "compress-40",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 40KB",
    desc: "Force file size under 40KB limit.",
    group: "compress",
    targetKB: 40,
  },
  {
    id: "compress-50",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 50KB",
    desc: "Force file size under 50KB limit.",
    group: "compress",
    targetKB: 50,
  },
  {
    id: "compress-100",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 100KB",
    desc: "Force file size under 100KB limit.",
    group: "compress",
    targetKB: 100,
  },
  {
    id: "compress-150",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 150KB",
    desc: "Force file size under 150KB limit.",
    group: "compress",
    targetKB: 150,
  },
  {
    id: "compress-200",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 200KB",
    desc: "Force file size under 200KB limit.",
    group: "compress",
    targetKB: 200,
  },
  {
    id: "compress-300",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 300KB",
    desc: "Force file size under 300KB limit.",
    group: "compress",
    targetKB: 300,
  },
  {
    id: "compress-500",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "JPEG to 500KB",
    desc: "Force file size under 500KB limit.",
    group: "compress",
    targetKB: 500,
  },
  {
    id: "compress-1mb",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 1MB",
    desc: "Force file size under 1MB limit.",
    group: "compress",
    targetKB: 1024,
  },
  {
    id: "compress-2mb",
    category: "target-sizes",
    icon: "fa-weight-hanging",
    title: "Compress to 2MB",
    desc: "Force file size under 2MB limit.",
    group: "compress",
    targetKB: 2048,
  },

  // ── 8. Resize Other Official Sizes (5) ───────────────────────────────────
  {
    id: "resize-a4",
    category: "official-sizes",
    icon: "fa-file-pdf",
    title: "A4 Size",
    desc: "Set size to standard A4 sheet dimensions.",
    group: "resize",
    defaultW: 21,
    defaultH: 29.7,
    unit: "cm",
  },
  {
    id: "ssc-photo",
    category: "official-sizes",
    icon: "fa-user-graduate",
    title: "SSC Photo Resize",
    desc: "Format photo to SSC specs (3.5x4.5cm).",
    group: "resize",
    defaultW: 3.5,
    defaultH: 4.5,
    unit: "cm",
    dpi: 300,
  },
  {
    id: "pan-card-resize",
    category: "official-sizes",
    icon: "fa-id-card-clip",
    title: "PAN Card",
    desc: "NSDL/UTI PAN size formatting.",
    group: "resize",
    defaultW: 2.5,
    defaultH: 3.5,
    unit: "cm",
    dpi: 300,
  },
  {
    id: "upsc-photo-resize",
    category: "official-sizes",
    icon: "fa-landmark",
    title: "UPSC Photo",
    desc: "Format photo to UPSC square specifications.",
    group: "resize",
    defaultW: 350,
    defaultH: 350,
    unit: "px",
    forceSquare: true,
  },
  {
    id: "psc-photo",
    category: "official-sizes",
    icon: "fa-building-columns",
    title: "PSC Photo",
    desc: "Resize photo for state Public Service Commissions.",
    group: "resize",
    defaultW: 3.5,
    defaultH: 4.5,
    unit: "cm",
  },
];

// Tool count verification — must equal 88
// 11 + 18 + 19 + 4 + 9 + 6 + 16 + 5 = 88 ✅
export const TOOL_COUNT = TOOLS.length; // 88

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getAllToolSlugs(): string[] {
  return TOOLS.map((t) => t.id);
}
